### ISSUE TITLE
CMake error: No such file or directory: PersonalFace.h.tmp

### ISSUE THREAD

**Issue by 5chdn** [ethereum/webthree#98] opened 2016-01-14 07:22 UTC
i can not compile https://github.com/ethereum/webthree-umbrella/issues/109 latest `develop` because cmake is missing several `*.tmp` files, here are the logs https://gist.github.com/5chdn/ef04a26216e12885eb5e

it refers to a missing:

```
./ethereum/webthree/libweb3jsonrpc/PersonalFace.h.tmp
```

i'm on archlinux kernel 4.2.5-1-ARCH x86_64 GNU/Linux. CMake version 3.4.1/Linux.

please check the logs and let me know if you need more details.

**Comment by bobsummerwill** [comment] 2016-01-14 07:48
Hey @5chdn,
Closing as a duplicate of https://github.com/ethereum/webthree-umbrella/issues/109.
I'm afraid that you are largely on your own with Arch Linux.
@LefterisJP has been making efforts to get it working too, but Ubuntu is the "official" distro.

**Closed as completed by bobsummerwill** 2016-01-14 07:48 UTC

**Comment by 5chdn** [comment] 2016-01-14 08:28
"thanks" for your "support". _rollseyes_

**Comment by bobsummerwill** [comment] 2016-01-14 08:41
Thanks for your sarcasm, @5chdn.

I shall be sure to apply precisely none of my unpaid volunteer effort to helping you in the future.

**Comment by 5chdn** [comment] 2016-01-14 08:56
_Ethereum is how the Internet was supposed to work*._ 

(*But you have to download Ubuntu first!!!!111) :p

**Comment by bobsummerwill** [comment] 2016-01-14 15:24
Ignoring your repeated immature comments, I would suggest that you install the Go client, which does have installation instructions for Arch Linux.

https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Arch
